In [1]:
import numpy as np


In [2]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

#### import data

Our CSV is ill formatted, i.e. separarted by ';' . Hence we will load the text.

In [3]:
raw_data_np = np.genfromtxt("datasets/loan-data.csv", delimiter=';', autostrip=True, encoding = "cp855")
raw_data_np

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

#### Checking for incomplete data

In [4]:
np.isnan(raw_data_np).sum()

88019

In [5]:
temp_fill = np.nanmax(raw_data_np)+1
temp_mean = np.nanmean(raw_data_np, axis=0)

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_9005/3416427304.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis=0)


Looking at the warning, we can say that there exists a column full of NAN. The genfromtext method casts string to NAN, which could have led to 
such large NANs.

In [6]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

Lets store the raw data stats in temporary variable. Create a new array and store the minimum, average, and the maximum values.

In [7]:
temp_stats = np.array([np.nanmin(raw_data_np, axis=0), temp_mean, np.nanmax(raw_data_np, axis=0)])
print(temp_stats.shape)
print(temp_stats)

(3, 14)
[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42
          nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
          nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97
          nan         nan         nan         nan         nan    41913.62]]


/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_9005/445344237.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis=0), temp_mean, np.nanmax(raw_data_np, axis=0)])


#### Splitting the datasetes (numeric and text)

First, Split the columns

In [8]:
columns_string = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [9]:
columns_numeric = np.argwhere(np.isnan(temp_mean)== False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

Importing data based on type

In [10]:
loan_data_string = np.genfromtxt("datasets/loan-data.csv", delimiter=';', skip_header=1, usecols=columns_string, dtype=np.str, encoding = "cp855")
loan_data_string

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_9005/83039153.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_string = np.genfromtxt("datasets/loan-data.csv", delimiter=';', skip_header=1, usecols=columns_string, dtype=np.str, encoding = "cp855")


array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
loan_data_numeric = np.genfromtxt("datasets/loan-data.csv", delimiter=';', skip_header=1, usecols=columns_numeric, filling_values=temp_fill, encoding = "cp855")
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

##### Column Names 

In [12]:
all_header = np.genfromtxt("datasets/loan-data.csv", delimiter=';', autostrip=True, skip_footer=raw_data_np.shape[0]-1, dtype=np.str, encoding="cp855")
all_header

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_9005/961697541.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  all_header = np.genfromtxt("datasets/loan-data.csv", delimiter=';', autostrip=True, skip_footer=raw_data_np.shape[0]-1, dtype=np.str, encoding="cp855")


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
header_numeric, header_string = all_header[columns_numeric], all_header[columns_string]
print(f"Numeric cols: {header_numeric}\nString cols: {header_string}")

Numeric cols: ['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']
String cols: ['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']


#### Checkpoints
Saving a copy of data, Just to avoid resourceful computations.

In [14]:
def checkpoint(file_name, header, data):
    np.savez("checkpoints/"+file_name, header=header, data=data)
    checkpoint_variables = np.load("checkpoints/"+file_name + '.npz')
    return(checkpoint_variables)

In [15]:
checkpoint_test = checkpoint("checkpoint_test", header_string, loan_data_string)

In [16]:
checkpoint_test['data']

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [17]:
np.array_equal(checkpoint_test['data'], loan_data_string)

True

### Manipulationg string columns

In [18]:
# lets make a variable descriptive
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Issue date

In [19]:
header_string[0] = "issued_date"
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

We can see "", i.e. empty value. We can see that the year is 2015. Hence we can strip the last 15 part of data without loosing insights.

In [20]:
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0], "-15")
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

Now, we represent the month values as an integer. (In order 1-12). It is memory efficient too.

In [21]:
# create a int type month to map
months = np.array(['', 'Jan', 'Feb', 'Mar','Apr', 'May', 'Jun', 'Jul','Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

# transforming data
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i], i, loan_data_string[:,0])

loan_data_string[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

#### Loan Status

In [22]:
header_string

array(['issued_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [23]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

We have nine possible loam states, including a missing data. We can use the previous approach to assign a corresponding number to each status. But, Here our main concerns is the customer is in stable financial conditions that is either good or bad. Hence, we assign a simple dummy indicator whether a customer is bad or good.

- Grouping techniques: 

1 GOOD: Fully Paid, Current, In grace Period, Issued, Short Latency

0 BAD: Charged Off, Defaulted, and Missing,  Long Latency

In [24]:
bad_status = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])
good_status = np.array(['Current', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)'])

In [25]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1], bad_status), 0,1 )

In [26]:
print(np.unique(loan_data_string[:,1]))
print(loan_data_string[:,1])

['0' '1']
['1' '1' '1' ... '1' '1' '1']


#### Term

In [27]:
header_string

array(['issued_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [28]:
np.unique(loan_data_string[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

we can strip the space and months text, and rename the column name just to better understand.

Since 6o months is worse term, and we take that to impute missing values.


In [29]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2], " months")
header_string[2] = "term_months"
loan_data_string[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [30]:
loan_data_string[:,2] = np.where(loan_data_string[:,2] == '', 60, loan_data_string[:,2])
loan_data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [31]:
# check the missing values
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

The term months values require more domain knowledge, we need to know why there are just a 36 and 60 months. At this situation, you might tempted to encode the values into binary. But, we will let it be as it is.

#### Grade and Subgrade

In [32]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [33]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [34]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

We have seven categories in Grade and subgrade is further categorized into 5 different of each subgroup. Any information from subgroup can also be obtained from group, which makes the group redundant. For instance, if a subgroup is missing for group B data, It would be wise to impute B5 rather than D5.

In [35]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '')& (loan_data_string[:,3] == i),
                                       i + '5', loan_data_string[:,4]
                                    )
loan_data_string[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [36]:
np.unique(loan_data_string[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

We can see that there is still 9 empty data instances. Since it is small in number, we can drop it. But, Here is the better idea, we can assign new 
category for that data instances.

In [37]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where(loan_data_string[:,4] == '',
                                       'H1', loan_data_string[:,4]
                                    )
np.unique(loan_data_string[:,4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

Now, we can remove the Grade column.

In [38]:
loan_data_string = np.delete(loan_data_string, 3, axis=1)
loan_data_string

array([['5', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [39]:
print(header_string)
header_string = np.delete(header_string, 3)
print(header_string)

['issued_date' 'loan_status' 'term_months' 'grade' 'sub_grade' 'verification_status' 'url'
 'addr_state']
['issued_date' 'loan_status' 'term_months' 'sub_grade' 'verification_status' 'url' 'addr_state']


Lets encode the subgroup. We are going to use key-value dict to map its value.

In [40]:
keys = list(np.unique(loan_data_string[:,3]))
values = list(range(1, np.unique(loan_data_string[:,3]).shape[0] + 1))
mapping = dict(zip(keys, values))
mapping

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [41]:
for i in np.unique(loan_data_string[:,3]):
    loan_data_string[:,3] = np.where(loan_data_string[:,3] == i, mapping[i], loan_data_string[:,3])

loan_data_string[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

In [42]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### Verification Status

In [43]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [44]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

Here, we can assume the missing values are not verified source. Hence, we group them into good and bad source, as we did for loan status. 

1 Verified 

0 Not verified

In [45]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') | (loan_data_string[:,4] == 'Not Verified'), 0 , 1)
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

#### URL

In [46]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

we can see the domain name is exact for url data. But, we have different loan_id associated with it. Lets verify this with loan ID, whether they are same or not.

In [47]:
# strip the data
loan_data_string[:,5] = np.chararray.strip(loan_data_string[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [48]:
all_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [49]:
loan_data_numeric[:,0][:5]

array([48010226., 57693261., 59432726., 53222800., 57803010.])

In [50]:
loan_data_string[:,5][:5]

array(['48010226', '57693261', '59432726', '53222800', '57803010'], dtype='<U69')

We are confirmed that both are exact except ID in numeric and URL id is text. Now can convert it into int but we can extract same information using ID column. Hence, we drop the URL column.

In [51]:
loan_data_string = np.delete(loan_data_string, 5, axis=1)
header_string = np.delete(header_string, 5)
print(loan_data_string[1,:])
print(header_string)

['0' '1' '36' '5' '1' 'NY']
['issued_date' 'loan_status' 'term_months' 'sub_grade' 'verification_status' 'addr_state']


#### State Address 

In [52]:
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [53]:
np.unique(loan_data_string[:,-1], return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27]))

We have missing state, IA. The values above are sorted based on State name. Lets, do sort them based on number of application.  

In [54]:
states_names, states_count = np.unique(loan_data_string[:,-1], return_counts=True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

Here, we can see the most of the accounts are from highly populated and wealthy area like CA, NY, TX, and FL. In contrast, we have very little data for too many states to examine individually. if we assign unique values to each state, this will allow outliers to have a big influence on the coefficients. Lets group them based on their characateristics.

In [55]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [56]:
# lets take care of missing values
loan_data_string[:,-1] = np.where(loan_data_string[:,-1] == '', 0 , loan_data_string[:,-1])
np.unique(loan_data_string[:,-1])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [57]:
loan_data_string[:,-1] = np.where(np.isin(loan_data_string[:,-1], states_west), 1, loan_data_string[:,-1])
loan_data_string[:,-1] = np.where(np.isin(loan_data_string[:,-1], states_south), 2, loan_data_string[:,-1])
loan_data_string[:,-1] = np.where(np.isin(loan_data_string[:,-1], states_midwest), 3, loan_data_string[:,-1])
loan_data_string[:,-1] = np.where(np.isin(loan_data_string[:,-1], states_east), 4, loan_data_string[:,-1])

In [58]:
np.unique(loan_data_string[:,-1])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [59]:
loan_data_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

Here, eventhough the data are numeric, they are represented as string. Lets convert them and save at a checkpoint.

In [60]:
loan_data_string = loan_data_string.astype(np.int)
loan_data_string

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_9005/4083221643.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_string = loan_data_string.astype(np.int)


array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [61]:
checkpoint_str = checkpoint("checkpoint_string", header_string, loan_data_string)

In [62]:
checkpoint_str['header']

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [63]:
# compare
np.array_equal(checkpoint_str['data'], loan_data_string)

True

### Manipulating Numerical Columns

In [64]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [65]:
np.isnan(loan_data_numeric).sum()

0

We already substituted the missing values with worst possible values. we need to track them.

In [66]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID
Here we need to compare ID values with temporary fill.

temp_fill = max  + 1 

temp_mean = data mean


#### Substituting filler values

In [67]:
temp_fill

68616520.0

In [68]:
np.isin(loan_data_numeric[:,0], temp_fill)

array([False, False, False, ..., False, False, False])

In [69]:
np.isin(loan_data_numeric[:,0], temp_fill).sum()

0

In [70]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

Extracting only numeric data [min, mean, max]

In [71]:
temp_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [72]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Funded Amount

In [73]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

Here, we are substituting the temp_fill values with minimum values of the column.

In [74]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temp_fill, temp_stats[0,columns_numeric[2]], loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loaned amount, interest rate, Total Payment, Installment

In [75]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [76]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temp_fill, temp_stats[0, columns_numeric[i]], loan_data_numeric[:,i])


In [77]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,        6.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,        6.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,        6.  ,       31.42,     2185.64],
       [46154151.  ,     1000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,        6.  ,      309.97,      301.9 ]])

### Currency Change

The exchange rate

In [78]:
EUR_USD = np.genfromtxt("datasets/EUR-USD.csv", autostrip=True, dtype=np.str)
EUR_USD

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_9005/393597384.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  EUR_USD = np.genfromtxt("datasets/EUR-USD.csv", autostrip=True, dtype=np.str)


array(['Open,High,Low,Close,Volume',
       '1.2098628282546997,1.2098628282546997,1.11055588722229,1.1287955045700073,0',
       '1.1287955045700073,1.1484194993972778,1.117680549621582,1.1205360889434814,0',
       '1.119795799255371,1.1240400075912476,1.0460032224655151,1.0830246210098267,0',
       '1.0741022825241089,1.1247594356536865,1.0521597862243652,1.1114321947097778,0',
       '1.1215037107467651,1.145304799079895,1.0821995735168457,1.0960345268249512,0',
       '1.095902442932129,1.1428401470184326,1.0888904333114624,1.122296690940857,0',
       '1.1134989261627197,1.1219995021820068,1.081270456314087,1.0939244031906128,0',
       '1.0969001054763794,1.1705996990203857,1.0850305557250977,1.1340054273605347,0',
       '1.1225990056991577,1.1460003852844238,1.1089695692062378,1.1255937814712524,0',
       '1.1171561479568481,1.1494200229644775,1.0910003185272217,1.100897192955017,0',
       '1.1024993658065796,1.1060001850128174,1.056400179862976,1.0583018064498901,0',
     

We now know, we only need closing price, and where it is. we will extract required data using following techniue. The exchange rates are in order. Hence, it will be easier to convert.

In [79]:
EUR_USD = np.genfromtxt("datasets/EUR-USD.csv",delimiter=',', autostrip=True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [80]:
# lets look at string column which have date
header_string

array(['issued_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

issued date is at 0 index. lets create an exchange rate for each month of 2015.

In [81]:
loan_data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [82]:
exchange_rate = loan_data_string[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i , EUR_USD[i-1], exchange_rate)

exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

we still have a data with no issued date i.e, 0. we will impute the values with annual exchange rate i.e, average of exchange rate.

In [83]:
exchange_rate = np.where(exchange_rate == 0 , np.mean(EUR_USD), exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

We need to concatenate the exchange rate to numeric data.

In [84]:
# lets check the shape
print(exchange_rate.shape)
print(loan_data_numeric.shape)

(10000,)
(10000, 6)


In [85]:
# reshape, and concat

exchange_rate = np.reshape(exchange_rate, (10000,1))
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [86]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,       31.42,     2185.64,        1.12],
       [46154151.  ,     1000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [87]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

Now, we are converting USD to EUR. The columns that are required to convert: 'loan_amount', 'funded_amount', 'installment', 'total_payment'. Lets select them and convert

In [88]:
dollar_columns = np.array([1,2,4,5])
loan_data_numeric[:, [dollar_columns]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,    31.42,  2185.64]],

       [[ 1000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [89]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

Since we have EUR-USD exchange rate, and we need to convert USD to EUR. We will devide the USD amount buy exchange rate.

In [90]:
for i in dollar_columns:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1)) ))

In [91]:
loan_data_numeric.shape

(10000, 11)

#### Expand the header

In [92]:
additional_header = np.array([col + '_EUR' for col in header_numeric[dollar_columns]])
additional_header

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [93]:
# let add the header to orignal header
header_numeric = np.concatenate((header_numeric, additional_header))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [94]:
header_numeric[dollar_columns] = np.array([col +' _USD' for col in header_numeric[dollar_columns]])
header_numeric


array(['id', 'loan_amnt _USD', 'funded_amnt _USD', 'int_rate', 'installment _USD',
       'total_pymnt _USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U19')

lets re-arrange the header.

In [97]:
index_order = [0,1,7,2,8,3,4,9,5,10,6]
header_numeric = header_numeric[index_order]

In [98]:
header_numeric

array(['id', 'loan_amnt _USD', 'loan_amnt_EUR', 'funded_amnt _USD', 'funded_amnt_EUR', 'int_rate',
       'installment _USD', 'installment_EUR', 'total_pymnt _USD', 'total_pymnt_EUR',
       'exchange_rate'], dtype='<U19')

In [99]:
loan_data_numeric[:, index_order]

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,     1000.  ,      899.74, ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [100]:
loan_data_numeric = loan_data_numeric[:,index_order]
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,     1000.  ,      899.74, ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

#### Interest Rate
Lets find out the column in belongs to.

In [101]:
header_numeric

array(['id', 'loan_amnt _USD', 'loan_amnt_EUR', 'funded_amnt _USD', 'funded_amnt_EUR', 'int_rate',
       'installment _USD', 'installment_EUR', 'total_pymnt _USD', 'total_pymnt_EUR',
       'exchange_rate'], dtype='<U19')

In [102]:
loan_data_numeric[:,5]

array([13.33,  6.  ,  6.  , ...,  6.  , 16.55,  6.  ])

The interest rates are not stored in 0-1 (fractual precentage). Lets transform them.

In [103]:
loan_data_numeric[:,5] = loan_data_numeric[:,5] /100 
loan_data_numeric[:,5]

array([0.13, 0.06, 0.06, ..., 0.06, 0.17, 0.06])

#### Checkpoint 2: Numeric

In [104]:
checkpoint_numeric = checkpoint('checkpoint_numeric', header_numeric, loan_data_numeric)

In [105]:
checkpoint_numeric['header']

array(['id', 'loan_amnt _USD', 'loan_amnt_EUR', 'funded_amnt _USD', 'funded_amnt_EUR', 'int_rate',
       'installment _USD', 'installment_EUR', 'total_pymnt _USD', 'total_pymnt_EUR',
       'exchange_rate'], dtype='<U19')

In [106]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,     1000.  ,      899.74, ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [107]:
np.array_equal(checkpoint_numeric['data'], loan_data_numeric)

True

#### Completing the dataset

In [108]:
checkpoint_str['data'].shape

(10000, 6)

In [109]:
checkpoint_numeric['data'].shape

(10000, 11)

In [113]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_str['data']))

In [114]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,     1000.  ,      899.74, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [115]:
np.isnan(loan_data).sum()

0

In [117]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_str['header']))
header_full

array(['id', 'loan_amnt _USD', 'loan_amnt_EUR', 'funded_amnt _USD', 'funded_amnt_EUR', 'int_rate',
       'installment _USD', 'installment_EUR', 'total_pymnt _USD', 'total_pymnt_EUR',
       'exchange_rate', 'issued_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'addr_state'], dtype='<U19')

#### Sorting the data

We wil use argsort on ID cloumn to sort the entire dataset.

In [118]:
loan_data[np.argsort(loan_data[:,0])]

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [119]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [120]:
# lets verify
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

#### Stacking and storing the complete data

In [122]:
loan_data = np.vstack((header_full, loan_data))
loan_data

array([['id', 'loan_amnt _USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [124]:
# Save data
np.savetxt("datasets/loan_data_preprocesssed.txt", loan_data, fmt="%s", delimiter=",")

In [125]:
print("Its is now ready for model building")

Its is now ready for model building
