In [1]:
import numpy as np


In [2]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

#### import data

Our CSV is ill formatted, i.e. separarted by ';' . Hence we will load the text.

In [5]:
raw_data_np = np.genfromtxt("datasets/loan-data.csv", delimiter=';', autostrip=True, encoding = "cp855")
raw_data_np

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

#### Checking for incomplete data

In [6]:
np.isnan(raw_data_np).sum()

88019

In [7]:
temp_fill = np.nanmax(raw_data_np)+1
temp_mean = np.nanmean(raw_data_np, axis=0)

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_3363/3416427304.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis=0)


Looking at the warning, we can say that there exists a column full of NAN. The genfromtext method casts string to NAN, which could have led to 
such large NANs.

In [8]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

Lets store the raw data stats in temporary variable. Create a new array and store the minimum, average, and the maximum values.

In [11]:
temp_stats = np.array([np.nanmin(raw_data_np, axis=0), temp_mean, np.nanmax(raw_data_np, axis=0)])
print(temp_stats.shape)
print(temp_stats)

(3, 14)
[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42
          nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
          nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97
          nan         nan         nan         nan         nan    41913.62]]


/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_3363/445344237.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis=0), temp_mean, np.nanmax(raw_data_np, axis=0)])


#### Splitting the datasetes (numeric and text)

First, Split the columns

In [13]:
columns_string = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [14]:
columns_numeric = np.argwhere(np.isnan(temp_mean)== False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

Importing data based on type

In [16]:
loan_data_string = np.genfromtxt("datasets/loan-data.csv", delimiter=';', skip_header=1, usecols=columns_string, dtype=np.str, encoding = "cp855")
loan_data_string

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_3363/83039153.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_string = np.genfromtxt("datasets/loan-data.csv", delimiter=';', skip_header=1, usecols=columns_string, dtype=np.str, encoding = "cp855")


array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [17]:
loan_data_numeric = np.genfromtxt("datasets/loan-data.csv", delimiter=';', skip_header=1, usecols=columns_numeric, filling_values=temp_fill, encoding = "cp855")
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

##### Column Names 

In [19]:
all_header = np.genfromtxt("datasets/loan-data.csv", delimiter=';', autostrip=True, skip_footer=raw_data_np.shape[0]-1, dtype=np.str, encoding="cp855")
all_header

/var/folders/1r/3db931yx4ys8zd46l5tbk6x80000gn/T/ipykernel_3363/961697541.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  all_header = np.genfromtxt("datasets/loan-data.csv", delimiter=';', autostrip=True, skip_footer=raw_data_np.shape[0]-1, dtype=np.str, encoding="cp855")


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [21]:
header_numeric, header_string = all_header[columns_numeric], all_header[columns_string]
print(f"Numeric cols: {header_numeric}\nString cols: {header_string}")

Numeric cols: ['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']
String cols: ['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']


#### Checkpoints
Saving a copy of data, Just to avoid resourceful computations.

In [24]:
def checkpoint(file_name, header, data):
    np.savez("checkpoints/"+file_name, header=header, data=data)
    checkpoint_variables = np.load("checkpoints/"+file_name + '.npz')
    return(checkpoint_variables)

In [25]:
checkpoint_test = checkpoint("checkpoint_test", header_string, loan_data_string)

In [26]:
checkpoint_test['data']

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [27]:
np.array_equal(checkpoint_test['data'], loan_data_string)

True

#### Manipulationg string columns

In [28]:
# lets make a variable descriptive
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Issue date

In [29]:
header_string[0] = "issued_date"
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

We can see "", i.e. empty value. We can see that the year is 2015. Hence we can strip the last 15 part of data without loosing insights.

In [32]:
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0], "-15")
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

Now, we represent the month values as an integer. (In order 1-12). It is memory efficient too.

In [33]:
# create a int type month to map
months = np.array(['', 'Jan', 'Feb', 'Mar','Apr', 'May', 'Jun', 'Jul','Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

# transforming data
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i], i, loan_data_string[:,0])

loan_data_string[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')